[workspace]
members = [
  "src/biwac_base",
  "src/biwac_lexer",
  "src/biwac_parser",
  "src/biwac_novel_parser",
  "src/biwac_package_loader",
  "src/biwac_lang_item",
  "src/biwac_hir",
  "src/biwac_name_resolver",
  "src/biwac_type_inferrer",
  "src/biwac_generator",
  "src/biwac_driver"
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
oxc_codegen = "0.113.0"
oxc_ast = "0.113.0"
oxc_span = "0.113.0"
oxc_allocator = "0.113.0"
oxc_parser = "0.113.0"

[workspace.features]
default = [ "typescript" ]
typescript = [ "biwac_generator/typescript" ]
