[package]
name = "biwac_generator"
version.workspace = true
edition.workspace = true

[dependencies]
biwac_base = { path = "../biwac_base"}
biwac_parser = { path = "../biwac_parser"}
biwac_package_loader = { path = "../biwac_package_loader"}
biwac_hir = { path = "../biwac_hir"}
oxc_codegen = { workspace = true, optional = true }
oxc_ast = { workspace = true, optional = true }
oxc_span = { workspace = true, optional = true }
oxc_allocator = { workspace = true, optional = true }
oxc_parser = { workspace = true, optional = true }

[features]
default = [ "typescript" ]
typescript = [ "dep:oxc_codegen", "dep:oxc_ast", "dep:oxc_span", "dep:oxc_allocator", "dep:oxc_parser" ]
