[package]
name = "biwac_name_resolver"
version.workspace = true
edition.workspace = true

[dependencies]
biwac_base = { path = "../biwac_base"}
biwac_ast = { path = "../biwac_ast"}
biwac_lexer = { path = "../biwac_lexer"}
biwac_package_loader = { path = "../biwac_package_loader"}
biwac_hir = { path = "../biwac_hir"}
