[package]
name = "biwac_package_loader"
version.workspace = true
edition.workspace = true

[dependencies]
biwac_base = { path = "../biwac_base"}
biwac_ast = { path = "../biwac_ast"}
biwac_parser = { path = "../biwac_parser"}
biwac_lexer = { path = "../biwac_lexer"}
biwac_metadata_loader = { path = "../biwac_metadata_loader"}
