[package]
name = "biwac_type_inferrer"
version.workspace = true
edition.workspace = true

[dependencies]
biwac_base = { path = "../biwac_base"}
biwac_parser = { path = "../biwac_parser"}
biwac_package_loader = { path = "../biwac_package_loader"}
biwac_hir = { path = "../biwac_hir"}
biwac_name_resolver = { path = "../biwac_name_resolver"}
