[package]
name = "biwac_type_inferrer"
version.workspace = true
edition.workspace = true

[dependencies]
biwac_base = { path = "../biwac_base"}
biwac_span = { path = "../biwac_span"}
biwac_ast = { path = "../biwac_ast"}
biwac_metadata_loader = { path = "../biwac_metadata_loader"}
biwac_package_loader = { path = "../biwac_package_loader"}
biwac_hir = { path = "../biwac_hir"}
biwac_name_resolver = { path = "../biwac_name_resolver"}
biwac_dependency_metadata = { path = "../biwac_dependency_metadata"}
