[package]
name = "biwac_parser"
version.workspace = true
edition.workspace = true

[dependencies]
biwac_base = { path = "../biwac_base"}
biwac_span = { path = "../biwac_span"}
biwac_lexer = { path = "../biwac_lexer"}
biwac_ast = { path = "../biwac_ast"}
biwac_novel_parser = { path = "../biwac_novel_parser"}
ariadne.workspace = true
