[package]
name = "biwac_mir"
version.workspace = true
edition.workspace = true

[dependencies]
biwac_base = { path = "../biwac_base"}
biwac_span = { path = "../biwac_span"}
biwac_hir = { path = "../biwac_hir"}
biwac_hash = { path = "../biwac_hash"}
biwac_dependency_metadata = { path = "../biwac_dependency_metadata"}
